[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "juv"
version = "0.5.0"
description = "A toolkit for reproducible Jupyter notebooks, powered by uv."
readme = "README.md"
authors = [{ name = "Trevor Manz", email = "trevor.j.manz@gmail.com" }]
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "click>=8.1.7",
    "jupytext>=1.16.4",
    "msgpack>=1.2.1",
    "Pygments>=2.20.0",
    "requests>=2.33.0",
    "rich>=13.9.2",
    "tomlkit>=0.13.2",
    "whenever>=0.9.1",
    "uv>=0.11.0",
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]

[project.scripts]
juv = "juv:main"

[dependency-groups]
dev = [
    "inline-snapshot>=0.13.3",
    "pytest>=9.0.3",
    "rooster>=0.1.1",
    "ruff>=0.7.0",
]
e2e = ["pytest-playwright>=0.5.2"]

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "TD",
    "FIX",
    "S404",
    "D203",
    "COM812",
    "ISC001",
    "D213",
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    "D",
    "S101",
    "SLF001",
    "W291",
    "INP001",
    "E501",
    "PLC2701",
]

[tool.rooster]
version_tag_prefix = ""
major_labels = []
minor_labels = ["breaking"]
changelog_ignore_labels = ["internal"]
changelog_sections.breaking = "Breaking changes"
changelog_sections.enhancement = "Enhancements"
changelog_sections.bug = "Bug fixes"
changelog_sections.documentation = "Documentation"
changelog_sections.__unknown__ = "Other changes"
changelog_contributors = true

[tool.inline-snapshot]
format-command = "ruff format --stdin-filename {filename}"

[tool.uv]
required-version = ">=0.11.0"
